ERP/ERP-war/src/java/et/gov/eep/fcms/controller/AccountsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller;

import et.gov.eep.commonApplications.utility.JsfUtil;
import et.gov.eep.fcms.businessLogic.AccountsBeanLocal;
import et.gov.eep.fcms.entity.FmsAccounts;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import org.primefaces.event.NodeSelectEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

/**
 *
 * @author mora1
 */
@Named(value = "accountsController")
@ViewScoped
public class AccountsController implements Serializable {

    /**
     * Creates a new instance of AccountsController
     */
    public AccountsController() {
    }

    @Inject
    FmsAccounts fmsAccounts;
    @EJB
    AccountsBeanLocal accountsBeanLocal;
    private TreeNode root;
    private TreeNode root2;
    private TreeNode selectedNode;
    private String SaveOrUpdateButton = "Save";
    private String createOrSearchBundle = "New";
    private String headerTitle = "Chart of Account Search";
    private String icone = "ui-icon-document";
    private boolean disableBtnCreate;
    private boolean disableParent=false;
    private boolean disableBtnSubsdery = false;
    private boolean renderPnlCreateGatePass = false;
    private boolean renderPnlManPage = true;
    private Boolean update = false;
    private List<FmsAccounts> fmsAccountsesall;
    List<String> ParentId;

    @PostConstruct
    public void init() {
        fmsAccountsesall = accountsBeanLocal.findAll();
        root = new DefaultTreeNode("Root", null);
        String id;
        id="0";
        recursive(fmsAccountsesall,id, root);
        root2 = getRoot();
    }
    private static List<FmsAccounts> araListe;

    public void recursive(List<FmsAccounts> liste, String id, TreeNode node) {
        araListe = new ArrayList<>();
        if (fmsAccountsesall != null) {
            for (FmsAccounts k : fmsAccountsesall) {
                if (k.getParentId() != null && (k.getParentId() == null ? id == null : k.getParentId().equals(id))) {
                    TreeNode childNode = new DefaultTreeNode(k.getAccountsCode()+ "-" + k.getAccountsTitle(), node);
                    araListe.add(k);
                    recursive(araListe, k.getAccountsCode(), childNode);
                }
            }
        }
    }

//<editor-fold defaultstate="collapsed" desc="Getter and Setter Methods">
    public FmsAccounts getFmsAccounts() {
        return fmsAccounts;
    }

    public void setFmsAccounts(FmsAccounts fmsAccounts) {
        this.fmsAccounts = fmsAccounts;
    }

    public String getCreateOrSearchBundle() {
        return createOrSearchBundle;
    }

    public void setCreateOrSearchBundle(String createOrSearchBundle) {
        this.createOrSearchBundle = createOrSearchBundle;
    }

    public String getHeaderTitle() {
        return headerTitle;
    }

    public void setHeaderTitle(String headerTitle) {
        this.headerTitle = headerTitle;
    }

    public String getIcone() {
        return icone;
    }

    public void setIcone(String icone) {
        this.icone = icone;
    }

    public boolean isDisableBtnCreate() {
        return disableBtnCreate;
    }

    public void setDisableBtnCreate(boolean disableBtnCreate) {
        this.disableBtnCreate = disableBtnCreate;
    }

    public boolean isDisableBtnSubsdery() {
        return disableBtnSubsdery;
    }

    public void setDisableBtnSubsdery(boolean disableBtnSubsdery) {
        this.disableBtnSubsdery = disableBtnSubsdery;
    }

    public boolean isDisableParent() {
        return disableParent;
    }

    public void setDisableParent(boolean disableParent) {
        this.disableParent = disableParent;
    }

    public static List<FmsAccounts> getAraListe() {
        return araListe;
    }

    public static void setAraListe(List<FmsAccounts> araListe) {
        AccountsController.araListe = araListe;
    }

    public boolean isRenderPnlCreateGatePass() {
        return renderPnlCreateGatePass;
    }

    public void setRenderPnlCreateGatePass(boolean renderPnlCreateGatePass) {
        this.renderPnlCreateGatePass = renderPnlCreateGatePass;
    }

    public boolean isRenderPnlManPage() {
        return renderPnlManPage;
    }

    public void setRenderPnlManPage(boolean renderPnlManPage) {
        this.renderPnlManPage = renderPnlManPage;
    }

    public String getSaveOrUpdateButton() {
        return SaveOrUpdateButton;
    }

    public void setSaveOrUpdateButton(String SaveOrUpdateButton) {
        this.SaveOrUpdateButton = SaveOrUpdateButton;
    }

    public List<FmsAccounts> getFmsAccountsesall() {
        return fmsAccountsesall;
    }

    public void setFmsAccountsesall(List<FmsAccounts> fmsAccountsesall) {
        this.fmsAccountsesall = accountsBeanLocal.findAll();
    }

    public TreeNode getRoot() {
        return root;
    }

    public void setRoot(TreeNode root) {
        this.root = root;
    }

    public TreeNode getRoot2() {
        return root2;
    }

    public void setRoot2(TreeNode root2) {
        this.root2 = root2;
    }

    public TreeNode getAccountRoot() {
        return accountRoot;
    }

    public void setAccountRoot(TreeNode accountRoot) {
        this.accountRoot = accountRoot;
    }

    public TreeNode getAccountSelectionNode() {
        return accountSelectionNode;
    }

    public void setAccountSelectionNode(TreeNode accountSelectionNode) {
        this.accountSelectionNode = accountSelectionNode;
    }

    public static List<FmsAccounts> getAllAccountses() {
        return allAccountses;
    }

    public static void setAllAccountses(List<FmsAccounts> allAccountses) {
        AccountsController.allAccountses = allAccountses;
    }

    public static List<FmsAccounts> getAccountses() {
        return accountses;
    }

    public static void setAccountses(List<FmsAccounts> accountses) {
        AccountsController.accountses = accountses;
    }

    public String getAllAccountUnitAsOne() {
        return allAccountUnitAsOne;
    }

    public void setAllAccountUnitAsOne(String allAccountUnitAsOne) {
        this.allAccountUnitAsOne = allAccountUnitAsOne;
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public List<String> getParentId() {
        return ParentId;
    }

    public void setParentId(List<String> ParentId) {
        this.ParentId = ParentId;
    }

    //</editor-fold> 
    public SelectItem[] getListAccounts() {
        return JsfUtil.getSelectItems(accountsBeanLocal.findAll(), true);
    }

    public void create() {
        if (update == false) {
            accountsBeanLocal.create(fmsAccounts);
            clear();
        } else {
            accountsBeanLocal.edit(fmsAccounts);
            clear();
        }
    }

    public List<FmsAccounts> fmsAccountses(FmsAccounts subsidiary) {
        return accountsBeanLocal.fmsAccountses(subsidiary);
    }

    public FmsAccounts fmsAccountsDitle(FmsAccounts fmsAccounts) {
        return accountsBeanLocal.fmsAccountsDitle(fmsAccounts);
    }

    public void createNewView() {
        disableBtnCreate = false;
        switch (createOrSearchBundle) {
            case "New":
                renderPnlCreateGatePass = true;
                renderPnlManPage = false;
                createOrSearchBundle = "Search";
                headerTitle = "Chart of Account Rgistration";
                setIcone("ui-icon-search");
                break;
            case "Search":
                renderPnlCreateGatePass = false;
                renderPnlManPage = true;
                createOrSearchBundle = "New";
                headerTitle = "Chart of Account Search";
                setIcone("ui-icon-document");
                break;
        }
    }

    //  <editor-fold defaultstate="collapsed" desc=" Getter & Setters ">
    public TreeNode getAddressRoot() {
        return accountRoot;
    }

    public void setAddressRoot(TreeNode accountRoot) {
        this.accountRoot = accountRoot;
    }

    public TreeNode getAddressSelectedNode() {
        return accountSelectionNode;
    }

    public void setAddressSelectedNode(TreeNode accountSelectionNode) {
        this.accountSelectionNode = accountSelectionNode;
    }

   //  </editor-fold>   
    //  <editor-fold defaultstate="collapsed" desc="Address Tree">
    private TreeNode accountRoot;
    private TreeNode accountSelectionNode;
    private static List<FmsAccounts> allAccountses;
    private static List<FmsAccounts> accountses;
    private String accountCode;
    private String allAccountUnitAsOne;

    public void loadAccountsTree() {
        allAccountses = accountsBeanLocal.findAll();
        accountRoot = new DefaultTreeNode("Root", null);
        String parent = "0";
        populateAccountsNode(allAccountses, parent, accountRoot);
    }

    public void populateAccountsNode(List<FmsAccounts> addressData, String id, TreeNode node) {
        accountses = new ArrayList<>();
        for (FmsAccounts k : getAllAccountses()) {
            if (k.getParentId() == id) {
                TreeNode childNode = new DefaultTreeNode(k.getAccountsCode()+ "=>" + k.getAccountsTitle(), node);
                accountses.add(k);
                populateAccountsNode(accountses, k.getAccountsCode(), childNode);
            }
        }
    }

    public void onNodeSelect(NodeSelectEvent event) {
        selectedNode = event.getTreeNode();
        accountCode = selectedNode.getData().toString().split("-")[0];

ERP/ERP-war/src/java/et/gov/eep/fcms/controller/Bond/FmsBondTypeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller.Bond;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;
import org.primefaces.event.SelectEvent;
import securityBean.SessionBean;
import webService.AAA;
import webService.EventEntry;
import webService.IAdministration;
import et.gov.eep.commonApplications.utility.JsfUtil;
import et.gov.eep.fcms.businessLogic.Bond.FmsBondTypeBeanLocal;
import et.gov.eep.fcms.entity.Bond.FmsBondType;

/**
 *
 * @author mora
 */
@Named(value = "FmsTypeController")
@ViewScoped
public class FmsBondTypeController implements Serializable {

    //<editor-fold defaultstate="collapsed" desc="Inject Entities and @ EJB">
    //Inject EJB

    @EJB
    private FmsBondTypeBeanLocal beanLocal;
    //Inject entities
    @Inject
    private FmsBondType BondType;
    @Inject
    SessionBean sessionBeanLocal;
//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="variables declaration">
    //Declaring instance variables

    private String createOrSearchBundle = "New";
    private String icone = "ui-icon-plus";
    private boolean renderPnlCreateAdditional = false;
    private boolean renderPnlManPage = true;
    private boolean disableBtnCreate;
    boolean disable = false;
    String saveUpdate = "Save";
    int updateStatus = 1;
    DataModel<FmsBondType> BondtypesDatamodel;
    private List<FmsBondType> Bondtypes;
//</editor-fold>

    List<FmsBondType> BondTypes() {
        if (Bondtypes == null) {
            Bondtypes = new ArrayList<>();
        }
        return Bondtypes;
    }
//<editor-fold defaultstate="collapsed" desc="Getter and Setter Methods">

    public FmsBondType getBondType() {
        if (BondType == null) {
            BondType = new FmsBondType();
        }
        return BondType;
    }

    public DataModel<FmsBondType> getBondtypesDatamodel() {
        if (BondtypesDatamodel == null) {
            BondtypesDatamodel = new ListDataModel<>();
        }
        return BondtypesDatamodel;
    }

    public void setBondtypesDatamodel(DataModel<FmsBondType> BondtypesDatamodel) {
        this.BondtypesDatamodel = BondtypesDatamodel;
    }

    public List<FmsBondType> getBondLiborlist() {
        return Bondtypes;
    }

    public void setBondLiborlist(List<FmsBondType> Bondtypes) {
        this.Bondtypes = Bondtypes;
    }

    public void setBondType(FmsBondType BondType) {
        this.BondType = BondType;
    }

    public String getSaveUpdate() {
        return saveUpdate;
    }

    public void setSaveUpdate(String saveUpdate) {
        this.saveUpdate = saveUpdate;
    }

    public int getUpdateStatus() {
        return updateStatus;
    }

    public void setUpdateStatus(int updateStatus) {
        this.updateStatus = updateStatus;
    }

    public boolean isDisableBtnCreate() {
        return disableBtnCreate;
    }

    public void setDisableBtnCreate(boolean disableBtnCreate) {
        this.disableBtnCreate = disableBtnCreate;
    }

    public String getCreateOrSearchBundle() {
        return createOrSearchBundle;
    }

    public void setCreateOrSearchBundle(String createOrSearchBundle) {
        this.createOrSearchBundle = createOrSearchBundle;
    }

    public boolean isRenderPnlCreateAdditional() {
        return renderPnlCreateAdditional;
    }

    public void setRenderPnlCreateAdditional(boolean renderPnlCreateAdditional) {
        this.renderPnlCreateAdditional = renderPnlCreateAdditional;
    }

    public boolean isRenderPnlManPage() {
        return renderPnlManPage;
    }

    public void setRenderPnlManPage(boolean renderPnlManPage) {
        this.renderPnlManPage = renderPnlManPage;
    }

    public String getIcone() {
        return icone;
    }

    public void setIcone(String icone) {
        this.icone = icone;
    }

    public boolean isDisable() {
        return disable;
    }

    public void setDisable(boolean disable) {
        this.disable = disable;
    }

    //</editor-fold> 
    //search Bond local by Bond type
    public ArrayList<FmsBondType> searchBondType(String BondTypeId) {
        ArrayList<FmsBondType> BondTypes = null;
        BondType.setBondTypeId(BondTypeId);
        BondTypes = beanLocal.searchBondType(BondType);
        return BondTypes;
    }

  //select event to get Bond type info from Bond local
    public void getImportationInfo(SelectEvent event) {
        BondType.setBondTypeId(event.getObject().toString());
        BondType = beanLocal.getBondTypeInfo(BondType);
        saveUpdate = "Update";
        updateStatus = 2;
    }

    // save method for Bond type
    public String saveFmsBondType() {
        try {
            AAA securityService = new AAA();
            IAdministration security = securityService.getMetadataExchangeHttpBindingIAdministration();
            String systemBundle = "cfg/securityServer";
            String dataset = securityBean.Utility.getBundleValue(systemBundle, "dataSet");
            if (security.checkAccess(sessionBeanLocal.getUserName(), "saveFmsBondType", dataset)) {
                if (updateStatus == 1) {
                    beanLocal.create(BondType);
                    JsfUtil.addSuccessMessage("operating Budget successfully register");
                } else {
                    beanLocal.edit(BondType);
                    JsfUtil.addSuccessMessage("operating Budget info is Edited");
                    saveUpdate = "Create";
                }
            } else {
                JsfUtil.addFatalMessage("You don't have appropriate permission, please contact the system administrator.");
                EventEntry eventEntry = new EventEntry();
                eventEntry.setSessionId(sessionBeanLocal.getSessionID());
                eventEntry.setUserId(sessionBeanLocal.getUserId());
                QName qualifiedName = new QName("", "project");
                JAXBElement<String> test = new JAXBElement<String>(qualifiedName, String.class, null, sessionBeanLocal.getUserName());
                eventEntry.setUserLogin(test);
//..... add more information by calling fields defined in the object 
                security.addEventLog(eventEntry, dataset);
            }
        } catch (Exception ex) {
        }
        saveUpdateClear();
        return null;
    }

    //save update clear method
    private void saveUpdateClear() {
        BondType = null;

    }

    //create and search render method
    public void createNewAdditionalAmount() {
        disableBtnCreate = false;
        if (createOrSearchBundle.equals("New")) {
            renderPnlCreateAdditional = true;
            renderPnlManPage = false;
            createOrSearchBundle = "Search";
            setIcone("ui-icon-search");
        } else if (createOrSearchBundle.equals("Search")) {
            renderPnlCreateAdditional = false;
            renderPnlManPage = true;
            createOrSearchBundle = "New";
            setIcone("ui-icon-plus");
        }
    }
}

ERP/ERP-war/web/erp/fcms/Bond/BondType.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../../../resources/templates/template.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="navigaion_content">   
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="../fcmsDashBoardnew.xhtml"><i class="fa fa-fw fa-dashboard"></i> <span> Dashboard</span><i class="fa fa-angle-double-left pull-right"></i></a>
        </li>
        <li>
            <a href="BondLibor.xhtml"><i class="fa fa-circle-o"></i>Bond Libor </a>
        </li>
        <li>
            <a href="BondForeign.xhtml"><i class="fa fa-circle-o"></i>Bond Foreign </a>
        </li>      
        <li>
            <a href="BondLocal.xhtml"><i class="fa fa-circle-o"></i>Bond Local </a>
        </li>
        <li>
            <a href="LocalRepayment.xhtml"><i class="fa fa-circle-o"></i>Bond Local Repayment </a>
        </li>
        <li>
            <a href="BondCoupon.xhtml"><i class="fa fa-circle-o"></i>Bond Coupon </a>
        </li>
        <li>
            <a href="BondCouponSchedule.xhtml"><i class="fa fa-circle-o"></i>Bond Coupon Schedule </a>
        </li>
    </ui:define>
    <ui:define name="contents">   
        <h:form id="frmToolbar"> 
            <p:toolbar style="background-color:white;border-color: white">
                <f:facet name="right">
                    <p:commandButton id="btnIcone" action="#{FmsTypeController.createNewAdditionalAmount()}" 
                                     icon="#{FmsTypeController.icone}" validateClient="true" style="background-color: white"
                                     process="@this" update="@this,:frmRegisterUI,:frmMainUI,:frmToolbar"
                                     title="#{FmsTypeController.createOrSearchBundle}" />
                    <span class="ui-separator">
                        <span class="ui-icon ui-icon-grip-dotted-vertical" />
                    </span> 
                    <a href="LuBondType.xhtml"><i class="fa fa-fw fa-refresh"></i></a>
                    <span class="ui-separator">
                        <span class="ui-icon ui-icon-grip-dotted-vertical" />
                    </span>
                    <a href="../../fcms/fcmsDashBoardnew.xhtml"><i class="fa fa-fw fa-dashboard"></i>  </a>
                    <span class="ui-separator" >
                        <span class="ui-icon ui-icon-grip-dotted-vertical" />
                    </span> 
                </f:facet>
            </p:toolbar>
        </h:form>
        <h:form id="frmMainUI">
            <h:panelGroup style="border: white; background-color: transparent" id="mainUI" rendered="#{FmsTypeController.renderPnlManPage}">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Bond Type Search</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="col-md-12 textBoxMargin6px">
                                    <div class="form-group form-horizontal">
                                        <h:outputLabel for="searchAutocomplete" class="control-label col-sm-4" value="Enter Bond Type Name:"></h:outputLabel> 
                                        <div class="col-sm-8">
                                            <p:autoComplete id="searchAutocomplete" 
                                                            value="#{FmsTypeController.bondType.bondName}"
                                                            completeMethod="#{FmsTypeController.searchType(name)}" 
                                                            minQueryLength="1"
                                                            style="font-family: 'Lucida Sans'; font-size: 11px; font-style: normal; font-weight: lighter;"
                                                            var="bondTyList" 
                                                            itemValue="#{bondTyList.name}" itemLabel="#{bondTyList}" 
                                                            size="20" emptyMessage="no data">
                                                <p:ajax  event="itemSelect"  
                                                         process="@form"
                                                         listener="#{FmsTypeController.getImportationInfo}"
                                                         update="@this,:frmRegisterUI,:frmMainUI,:frmToolbar" />   
                                            </p:autoComplete> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </h:panelGroup>
        </h:form>
        <!-- Registration Form-->
        <h:form id="frmRegisterUI">
            <p:growl id="growl" showDetail="true" autoUpdate="true" severity="information,fatal"/>  
            <h:panelGroup style="border: 0px; background-color: transparent" id="registerUI" 
                          rendered="#{FmsTypeController.renderPnlCreateAdditional}" >
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Bond Type Registration </h3>
                    </div>
                    <div class="box-body">
                        <div class="col-md-12">
                            <div class="col-md-6">
                                <div class="col-md-12 textBoxMargin6px">
                                    <div class="form-group form-horizontal">
                                        <h:outputLabel for="txtbondTypeId" class="control-label col-sm-4" value="Name:"></h:outputLabel> 
                                        <div class="col-sm-8">
                                            <p:inputText id="txtbondTypeId"   value="#{FmsTypeController.luBondType.name}"
                                                         class="form-control"  style="background-color: white" converterMessage="Amount must be anumber" 
                                                         validatorMessage="Amount must be anumber"
                                                         title="TypeId" required="true" requiredMessage="The Name field is required." >
                                                <p:message for="txtbondTypeId" display="icon"/>
                                                <f:validateRegex pattern="^[a-zA-Z ]+$" />    </p:inputText>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 textBoxMargin6px">
                                    <div class="form-group form-horizontal">
                                        <h:outputLabel for="txtbondName" class="control-label col-sm-4" value="Description :"></h:outputLabel> 
                                        <div class="col-sm-8">
                                            <p:inputText id="txtbondName" value="#{FmsTypeController.luBondType.dscribtion}"  
                                                         class="form-control"  style="background-color: white" title="EmpId" required="true" 
                                                         requiredMessage="The Balance field is required"
                                                         >
                                            </p:inputText>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 textBoxMargin6px">
                                    <div class="form-group form-horizontal">
                                        <h:outputLabel id="lblBtnSave" class="control-label col-sm-4"/>
                                        <div class="col-sm-8">
                                            <p:commandButton id="btnsave" class="btn btn-primary"
                                                             action="#{FmsTypeController.saveFmsBondType}"
                                                             value="#{FmsTypeController.saveUpdate}"
                                                             process="@form"
                                                             update=":frmRegisterUI"/>
                                        </div>                                                   
                                    </div>       
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </h:panelGroup>                                          
        </h:form>
    </ui:define>
</ui:composition>