ERP/ERP-war/src/java/et/gov/eep/fcms/controller/AccountsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller;

import et.gov.eep.commonApplications.utility.JsfUtil;
import et.gov.eep.fcms.businessLogic.AccountsBeanLocal;
import et.gov.eep.fcms.entity.FmsAccounts;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import org.primefaces.event.NodeSelectEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

/**
 *
 * @author mora1
 */
@Named(value = "accountsController")
@ViewScoped
public class AccountsController implements Serializable {

    /**
     * Creates a new instance of AccountsController
     */
    public AccountsController() {
    }

    @Inject
    FmsAccounts fmsAccounts;
    @EJB
    AccountsBeanLocal accountsBeanLocal;
    private TreeNode root;
    private TreeNode root2;
    private TreeNode selectedNode;
    private String SaveOrUpdateButton = "Save";
    private String createOrSearchBundle = "New";
    private String headerTitle = "Chart of Account Search";
    private String icone = "ui-icon-document";
    private boolean disableBtnCreate;
    private boolean disableParent=false;
    private boolean disableBtnSubsdery = false;
    private boolean renderPnlCreateGatePass = false;
    private boolean renderPnlManPage = true;
    private Boolean update = false;
    private List<FmsAccounts> fmsAccountsesall;
    List<String> ParentId;

    @PostConstruct
    public void init() {
        fmsAccountsesall = accountsBeanLocal.findAll();
        root = new DefaultTreeNode("Root", null);
        String id;
        id="0";
        recursive(fmsAccountsesall,id, root);
        root2 = getRoot();
    }
    private static List<FmsAccounts> araListe;

    public void recursive(List<FmsAccounts> liste, String id, TreeNode node) {
        araListe = new ArrayList<>();
        if (fmsAccountsesall != null) {
            for (FmsAccounts k : fmsAccountsesall) {
                if (k.getParentId() != null && (k.getParentId() == null ? id == null : k.getParentId().equals(id))) {
                    TreeNode childNode = new DefaultTreeNode(k.getAccountsCode()+ "-" + k.getAccountsTitle(), node);
                    araListe.add(k);
                    recursive(araListe, k.getAccountsCode(), childNode);
                }
            }
        }
    }

//<editor-fold defaultstate="collapsed" desc="Getter and Setter Methods">
    public FmsAccounts getFmsAccounts() {
        return fmsAccounts;
    }

    public void setFmsAccounts(FmsAccounts fmsAccounts) {
        this.fmsAccounts = fmsAccounts;
    }

    public String getCreateOrSearchBundle() {
        return createOrSearchBundle;
    }

    public void setCreateOrSearchBundle(String createOrSearchBundle) {
        this.createOrSearchBundle = createOrSearchBundle;
    }

    public String getHeaderTitle() {
        return headerTitle;
    }

    public void setHeaderTitle(String headerTitle) {
        this.headerTitle = headerTitle;
    }

    public String getIcone() {
        return icone;
    }

    public void setIcone(String icone) {
        this.icone = icone;
    }

    public boolean isDisableBtnCreate() {
        return disableBtnCreate;
    }

    public void setDisableBtnCreate(boolean disableBtnCreate) {
        this.disableBtnCreate = disableBtnCreate;
    }

    public boolean isDisableBtnSubsdery() {
        return disableBtnSubsdery;
    }

    public void setDisableBtnSubsdery(boolean disableBtnSubsdery) {
        this.disableBtnSubsdery = disableBtnSubsdery;
    }

    public boolean isDisableParent() {
        return disableParent;
    }

    public void setDisableParent(boolean disableParent) {
        this.disableParent = disableParent;
    }

    public static List<FmsAccounts> getAraListe() {
        return araListe;
    }

    public static void setAraListe(List<FmsAccounts> araListe) {
        AccountsController.araListe = araListe;
    }

    public boolean isRenderPnlCreateGatePass() {
        return renderPnlCreateGatePass;
    }

    public void setRenderPnlCreateGatePass(boolean renderPnlCreateGatePass) {
        this.renderPnlCreateGatePass = renderPnlCreateGatePass;
    }

    public boolean isRenderPnlManPage() {
        return renderPnlManPage;
    }

    public void setRenderPnlManPage(boolean renderPnlManPage) {
        this.renderPnlManPage = renderPnlManPage;
    }

    public String getSaveOrUpdateButton() {
        return SaveOrUpdateButton;
    }

    public void setSaveOrUpdateButton(String SaveOrUpdateButton) {
        this.SaveOrUpdateButton = SaveOrUpdateButton;
    }

    public List<FmsAccounts> getFmsAccountsesall() {
        return fmsAccountsesall;
    }

    public void setFmsAccountsesall(List<FmsAccounts> fmsAccountsesall) {
        this.fmsAccountsesall = accountsBeanLocal.findAll();
    }

    public TreeNode getRoot() {
        return root;
    }

    public void setRoot(TreeNode root) {
        this.root = root;
    }

    public TreeNode getRoot2() {
        return root2;
    }

    public void setRoot2(TreeNode root2) {
        this.root2 = root2;
    }

    public TreeNode getAccountRoot() {
        return accountRoot;
    }

    public void setAccountRoot(TreeNode accountRoot) {
        this.accountRoot = accountRoot;
    }

    public TreeNode getAccountSelectionNode() {
        return accountSelectionNode;
    }

    public void setAccountSelectionNode(TreeNode accountSelectionNode) {
        this.accountSelectionNode = accountSelectionNode;
    }

    public static List<FmsAccounts> getAllAccountses() {
        return allAccountses;
    }

    public static void setAllAccountses(List<FmsAccounts> allAccountses) {
        AccountsController.allAccountses = allAccountses;
    }

    public static List<FmsAccounts> getAccountses() {
        return accountses;
    }

    public static void setAccountses(List<FmsAccounts> accountses) {
        AccountsController.accountses = accountses;
    }

    public String getAllAccountUnitAsOne() {
        return allAccountUnitAsOne;
    }

    public void setAllAccountUnitAsOne(String allAccountUnitAsOne) {
        this.allAccountUnitAsOne = allAccountUnitAsOne;
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public List<String> getParentId() {
        return ParentId;
    }

    public void setParentId(List<String> ParentId) {
        this.ParentId = ParentId;
    }

    //</editor-fold> 
    public SelectItem[] getListAccounts() {
        return JsfUtil.getSelectItems(accountsBeanLocal.findAll(), true);
    }

    public void create() {
        if (update == false) {
            accountsBeanLocal.create(fmsAccounts);
            clear();
        } else {
            accountsBeanLocal.edit(fmsAccounts);
            clear();
        }
    }

    public List<FmsAccounts> fmsAccountses(FmsAccounts subsidiary) {
        return accountsBeanLocal.fmsAccountses(subsidiary);
    }

    public FmsAccounts fmsAccountsDitle(FmsAccounts fmsAccounts) {
        return accountsBeanLocal.fmsAccountsDitle(fmsAccounts);
    }

    public void createNewView() {
        disableBtnCreate = false;
        switch (createOrSearchBundle) {
            case "New":
                renderPnlCreateGatePass = true;
                renderPnlManPage = false;
                createOrSearchBundle = "Search";
                headerTitle = "Chart of Account Rgistration";
                setIcone("ui-icon-search");
                break;
            case "Search":
                renderPnlCreateGatePass = false;
                renderPnlManPage = true;
                createOrSearchBundle = "New";
                headerTitle = "Chart of Account Search";
                setIcone("ui-icon-document");
                break;
        }
    }

    //  <editor-fold defaultstate="collapsed" desc=" Getter & Setters ">
    public TreeNode getAddressRoot() {
        return accountRoot;
    }

    public void setAddressRoot(TreeNode accountRoot) {
        this.accountRoot = accountRoot;
    }

    public TreeNode getAddressSelectedNode() {
        return accountSelectionNode;
    }

    public void setAddressSelectedNode(TreeNode accountSelectionNode) {
        this.accountSelectionNode = accountSelectionNode;
    }

   //  </editor-fold>   
    //  <editor-fold defaultstate="collapsed" desc="Address Tree">
    private TreeNode accountRoot;
    private TreeNode accountSelectionNode;
    private static List<FmsAccounts> allAccountses;
    private static List<FmsAccounts> accountses;
    private String accountCode;
    private String allAccountUnitAsOne;

    public void loadAccountsTree() {
        allAccountses = accountsBeanLocal.findAll();
        accountRoot = new DefaultTreeNode("Root", null);
        String parent = "0";
        populateAccountsNode(allAccountses, parent, accountRoot);
    }

    public void populateAccountsNode(List<FmsAccounts> addressData, String id, TreeNode node) {
        accountses = new ArrayList<>();
        for (FmsAccounts k : getAllAccountses()) {
            if (k.getParentId() == id) {
                TreeNode childNode = new DefaultTreeNode(k.getAccountsCode()+ "=>" + k.getAccountsTitle(), node);
                accountses.add(k);
                populateAccountsNode(accountses, k.getAccountsCode(), childNode);
            }
        }
    }

    public void onNodeSelect(NodeSelectEvent event) {
        selectedNode = event.getTreeNode();
        accountCode = selectedNode.getData().toString().split("-")[0];

ERP/ERP-war/src/java/et/gov/eep/fcms/controller/FmsTaxRateRegController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller;

import et.gov.eep.fcms.mapper.FmsTaxRateRegisterFacade;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.*;
import javax.ejb.EJB;

import et.gov.eep.fcms.entity.FmsTaxRateRegister;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;

/**
 *
 * @author kaleab
 */
@Named(value = "fmsTaxRateRegController")
@ViewScoped
public class FmsTaxRateRegController implements Serializable {
    @EJB
    private FmsTaxRateRegisterFacade fmsTaxRateRegisterFacade;

    private FmsTaxRateRegister taxRete =  new FmsTaxRateRegister();

    public FmsTaxRateRegister getTaxRete() {
        return taxRete;
    }

    public void setTaxRete(FmsTaxRateRegister taxRete) {
        this.taxRete = taxRete;
    }
    
    public FmsTaxRateRegController() {
    }
   public List<FmsTaxRateRegister> findAll(){
        return this.fmsTaxRateRegisterFacade.findAll();
    }
   
}

ERP/ERP-war/src/java/et/gov/eep/fcms/controller/Ifrs/FinancialAssetTypeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller.Ifrs;

import java.io.Serializable;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author mz
 */
@Named(value = "financialAssetTypeController")
@ViewScoped
public class FinancialAssetTypeController implements Serializable {

    /**
     * Creates a new instance of FinancialAssetTypeController
     */
    public FinancialAssetTypeController() {
    }
    
}

ERP/ERP-war/src/java/et/gov/eep/fcms/controller/Ifrs/FinancialInstrumentMeasureController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller.Ifrs;

import java.io.Serializable;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author mz
 */
@Named(value = "financialInstrumentMeasureController")
@ViewScoped
public class FinancialInstrumentMeasureController implements Serializable{

    /**
     * Creates a new instance of FinancialInstrumentMeasureController
     */
    public FinancialInstrumentMeasureController() {
    }
    
}

ERP/ERP-war/src/java/et/gov/eep/fcms/controller/Ifrs/FinancialInstrumentTypeController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package et.gov.eep.fcms.controller.Ifrs;

import java.io.Serializable;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author mz
 */
@Named(value = "financialInstrumentTypeController")
@ViewScoped
public class FinancialInstrumentTypeController implements Serializable {

    /**
     * Creates a new instance of FinancialInstrumentTypeController
     */
    public FinancialInstrumentTypeController() {
    }
    
}

ERP/ERP-war/src/java/securityBean/SessionBean.java
package securityBean;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import org.primefaces.model.StreamedContent;
import webService.UserStatus;

/**
 *
 * @author admin
 */
@Named("sessionBean")
@SessionScoped
public class SessionBean implements Serializable {

    @PostConstruct
    public void _init() {

    }

    //*** Session String Values ***********************
    private String _userName = "UserID";
    private int _userId = -1;
    private int _sessionID = 0;
    private int empId = -1;
    private String firstName = "";
    private String lastName = "";
    private String middleName;
    private String workId;
    private String loggerLine;
   

    /**
     * <p>
     * Construct a new session data bean instance.</p>
     */
//<editor-fold defaultstate="collapsed" desc="getter and setter">
    public SessionBean() {
        this.getPermission();
//        this.employeeInformation();
    }
    
    private StreamedContent content;
    
    public StreamedContent getContent() {
        return content;
    }
    
    public void setContent(StreamedContent content) {
        this.content = content;
    }
    
    public String getUserName() {
        return _userName;
    }
    
    public void setUserName(String _userName) {
        this._userName = _userName;
    }
    
    public int getUserId() {
        return _userId;
    }
    
    public void setUserId(int _userId) {
        this._userId = _userId;
    }
    
    public int getSessionID() {
        return _sessionID;
    }
    
    public void setSessionID(int _sessionID) {
        this._sessionID = _sessionID;
    }
    
    private String captcha = "";
    
    public String getCaptcha() {
        return captcha;
    }
    
    public void setCaptcha(String captcha) {
        this.captcha = captcha;
    }
    
    private UserStatus permissions;
    
    public UserStatus getPermissions() {
        return permissions;
    }
    
    public void setPermissions(UserStatus permissions) {
        this.permissions = permissions;
    }
    public int getEmpId() {
        return empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    
    public String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String getLastName() {
        return lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String getMiddleName() {
        return middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    
    public String getWorkId() {
        return workId;
    }
    
    public void setWorkId(String workId) {
        this.workId = workId;
    }
      public String getLoggerLine() {
        if (_userName.equalsIgnoreCase("UserID")) {
            loggerLine = "Offline";
        } else {
            loggerLine = "Online";

        }
        return loggerLine;
    }

    public void setLoggerLine(String loggerLine) {
        this.loggerLine = loggerLine;
    }
//</editor-fold>

    public UserStatus getPermission() {
        FacesContext context = FacesContext.getCurrentInstance();
        if (context != null) {
            HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
            if (request.getSession().getAttribute("permission") != null) {
                permissions = (UserStatus) request.getSession().getAttribute("permission");
            }
        }
        return permissions;
    }

 

  

}

ERP/ERP-war/web/erp/fcms/Voucher/postingChpv.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="../../../resources/templates/template.xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="navigaion_content">
        <li>
            <a href="../../fcms/Voucher/JournalVoucherReg.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Journal Voucher</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/cashReceiptVoucher.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Cash Receipt</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/ChequePayment.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Cheque Payment Voucher </a>
        </li>
        <li>
            <a href="../../fcms/Voucher/cashPaymentOrder.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Cash Order</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/postingCpo.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Posting Cash Order</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/fmswithHoldingVoucher.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Withholding Voucher </a>
        </li>
        <li>
            <a href="../../fcms/Voucher/postingCrv.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Posting cash Receipt</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/postingJv.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Posting Journal Voucher</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/LedgerReport.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Ledger Report </a>
        </li>
        <li>
            <a href="../../fcms/Voucher/TrialBalance.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Trial Balance Report</a>
        </li>
        <li>
            <a href="../../fcms/Voucher/VatVoucher.xhtml"><i class="fa fa-fw fa-circle-o-notch"></i>Vat Voucher</a>
        </li>
    </ui:define>
    <ui:define name="contents">
        <h:form id="frmToolbar"> 
            <p:toolbar style="background-color:white;border-color: white">
                <f:facet name="right">
                    <a href="ChequePayment.xhtml"><i class="fa fa-fw fa-refresh" title="Refresh"></i></a>
                    <span class="ui-separator">
                        <span class="ui-icon ui-icon-grip-dotted-vertical" />
                    </span>
                    <a href="../../fcms/fcmsDashBoardnew.xhtml"><i class="fa fa-fw fa-dashboard" title="Dashboard"></i>  </a>
                    <span class="ui-separator">
                        <span class="ui-icon ui-icon-grip-dotted-vertical"/>
                    </span>
                    <a href="../../../HomePage.xhtml"><i class="fa fa-home" title="Home Page"></i></a>
                    <span class="ui-separator" >
                        <span class="ui-icon ui-icon-grip-dotted-vertical" />
                    </span> 
                </f:facet>
            </p:toolbar>
        </h:form>
        <h:form  id="cpvForm" class="form-horizontal"> 
            <p:growl id="growl" showDetail="true" autoUpdate="true" severity="information,error"/>  
            <!--account use datatable--> 
            <div class="box box-primary">

                <div class="box-header with-border">
                    <h3 class="box-title">#{FCMS.Cheque_Payment_Voucher_Posting} </h3>
                </div>
                <div class="box-body">
                    <div class="form-group col-sm-10">
                        <div class="form-horizontal col-sm-8" style="padding-bottom: 10px;" >
                            <div class="col-md-12 ">
                                <div class="col-sm-3">
                                    <p:commandButton id="btnjenerit"  class="btn  btn-block btn-primary col-lg-4"                                                    
                                                     value="#{FCMS.View}" 
                                                     action="#{postingChequePaymentVoucherController.generatePostingChpv()}"
                                                     update=":cpvForm"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-horizontal  col-sm-12">                            
                        <div class="form-group">
                            <p:dataTable style="margin-bottom:0" id="tblAccountUsefoDetail" value="#{postingChequePaymentVoucherController.vouchersDetailDataModel}"
                                         var="voucherDetail"  paginator="true" paginatorPosition="bottom"  rowIndexVar="num" scrollHeight="700"  
                                         rowKey ="#{voucherDetail.voucherId}"  selection="#{postingChequePaymentVoucherController.selectedVouches}">
                                <p:ajax event="rowSelect" listener="#{postingChequePaymentVoucherController.check}" update=":cpvForm:tblAccountUsefoDetail" />  
                                <p:ajax event="rowUnselect" listener="#{postingChequePaymentVoucherController.uncheck}" update=":cpvForm:tblAccountUsefoDetail"/> 
                                <p:column selectionMode="multiple" style="width:16px;text-align:center"/>
                                <p:column id="test"  style="width:50px;text-align:left">                                    
                                    <f:facet name="header">
                                        <h:outputLabel  id="outputText1" value="#{FCMS.Voucher_Id}"/>
                                    </f:facet>
                                    <h:outputText id="outputText2064" value="#{voucherDetail.voucherId}"/>
                                </p:column>
                                <p:column id="test2" style="width:150px;text-align:left" >                                    
                                    <f:facet name="header">
                                        <h:outputLabel id="outputText3" value="#{FCMS.Purpose}"/>
                                    </f:facet>
                                    <h:outputText id="outputTexrert30" value="#{voucherDetail.purpose}"/>
                                </p:column>
                                <p:rowExpansion id="rowexpaId">
                                    <p:dataTable id="tblAccountUsefoDetail1" class="table table-no-select-all " value="#{postingChequePaymentVoucherController.accountUseDetailDataModelposting}" 
                                                 var="accountUseDetail" editable="true" editMode="cell"  paginator="true" paginatorPosition="bottom" rowIndexVar="num" lazy="true" rows="5">
                                        <p:column >
                                            <f:facet name="header">
                                                <h:outputText value="#{msg.SNo}"/>
                                            </f:facet>
                                            <h:outputText value="#{num+1}"/>
                                        </p:column>
                                        <p:column  headerText="#{FCMS.Account_Code}">                                    
                                            <f:facet name="header"><h:outputText value="Account Code"/></f:facet>
                                            <h:outputLabel  id="outputText2" value="#{accountUseDetail.display_conn}"/>
                                        </p:column>
                                        <p:column  headerText="Debit">                                    
                                            <p:cellEditor>
                                                <f:facet name="output"><h:outputLabel  id="outputText22" converter="#{postingChequePaymentVoucherController.numberConverter}"  value="#{accountUseDetail.debit}"/></f:facet>
                                                <f:facet name="input"><p:inputText id="inputText22" value="#{accountUseDetail.debit}"/> </f:facet>
                                            </p:cellEditor>
                                        </p:column>
                                        <p:column  headerText="Credt">                                    
                                            <p:cellEditor>
                                                <f:facet name="output"><h:outputLabel  id="outputText23" converter="#{postingChequePaymentVoucherController.numberConverter}"  value="#{accountUseDetail.credit}"/></f:facet>
                                                <f:facet name="input"><p:inputText id="inputText23" value="#{accountUseDetail.credit}"/> </f:facet>
                                            </p:cellEditor>
                                        </p:column>
                                    </p:dataTable> 
                                    <p:contextMenu for="tblAccountUsefoDetail1" widgetVar="cMenu">   
                                        <p:menuitem value="Edit Cell" icon="ui-icon-search" onclick="PF('cellCars').showCellEditor();
                                                return false;"/>  
                                        <p:menuitem value="Hide Menu" icon="ui-icon-close" onclick="PF('cMenu').hide()"/>  
                                    </p:contextMenu> 
                                </p:rowExpansion>
                            </p:dataTable> 
                        </div>
                    </div> 
                    <div class="form-group textBoxMargin6px">
                        <div class="col-sm-8">
                            <p:outputLabel value="#{FCMS.Processed_By}:" class="control-label col-sm-2"/>
                            <div class="col-sm-4">
                                <p:inputText  readonly="true" class="form-control col-sm-2" value="#{workFlow.userName}"/>
                            </div>
                            <p:outputLabel value="#{FCMS.Processed_Date}:" class="control-label col-sm-2"/>
                            <div class="col-sm-4">
                                <p:calendar  id="calProcessedDate" placeholder="MM/DD/YYYY" pattern="mm/dd/yyyy" value="#{postingChequePaymentVoucherController.fmsVoucher.processedDate}">
                                    <f:convertDateTime pattern="mm/dd/yyyy"/>
                                </p:calendar>
                            </div>
                        </div>
                    </div>   
                    <div class="form-group col-sm-10">
                        <div class="form-horizontal col-sm-8" style="padding-bottom: 10px;" >
                            <div class="col-md-12 ">
                                <div class="col-sm-3">
                                    <p:commandButton id="btnPost" class="btn  btn-block btn-primary col-lg-4"                                                    
                                                     value="#{FCMS.POST}" update=":cpvForm"
                                                     action="#{postingChequePaymentVoucherController.post_chequePaymentVoucher_data()}"/>
                                </div>
                                <div class="col-sm-3">
                                    <p:commandButton id="btnvoid"  class="btn  btn-block btn-primary col-lg-4"                                                    
                                                     value="#{FCMS.VOID}" 
                                                     onclick="PF('confirmation').show()" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <p:growl id="message" showDetail="true" />
                    <p:confirmDialog id="confirmDialog" message="Are you sure about void the voucher?"  
                                     header="Initiating void process" severity="alert" widgetVar="confirmation" >
                        <h:outputLabel class="control-label col-sm-4"  value="Reason:"/>
                        <p:column headerText="Reason">
                            <h:inputTextarea id="txtAreaReason1" value="#{postingChequePaymentVoucherController.fmsVoucher.reason}" 
                                             class="form-control"
                                             style="width: 100%" > 
                            </h:inputTextarea>
                        </p:column> 
                        <p:commandButton id="btnConfirm" value="Yes Sure" oncomplete="PF('confirmation').hide()"
                                         actionListener="#{postingChequePaymentVoucherController.void_chequePaymentVoucher_data()}" />  
                        <p:commandButton id="btnDecline" value="Not Yet" onclick="PF('confirmation').hide()" type="button" />   
                    </p:confirmDialog> 

                </div>
            </div>
        </h:form>          
    </ui:define>

</ui:composition>          